title:
description: 'a curated repository of classic accessories'
baseurl: /store
url: 'https://bovinealex.github.io'

# Jekyll-Store Engine
defaultAddress:
  country: US
payment:
  currency: USD
  hook: 'https://jekyll-store-microservice.herokuapp.com/purchase'
tracking_id: 'UA-62379004-1'

# Jekll-Store Front
image_prefix: 'https://res.cloudinary.com/dyblk8reo/image/upload/'
paymillPublicKey: ay83X48C3FAeX6k4keOyPpY2EXU
wake_up: 'http://jekyll-store-microservice.herokuapp.com/ping'
disqus_shortname: 'jekyll-store'

# http://openexchangerates.github.io/accounting.js/#documentation
accounting:
  symbol : '$'
  format: '%s%v'
  decimal : '.'
  thousand: ','
  precision : 2

# https://github.com/prose/prose/wiki/Prose-Configuration
prose:
  ignore:
    - _includes
    - _layouts
    - assets
    - json
    - node_modules
    - pages
    - .gitignore
    - _config.yml
    - CNAME
    - Gemfile
    - package.json
    - README.md
  metadata:
    _products:
      - name: name
        field:
          element: text
          label: Name
          help: Must be unique
      - name: price
        field:
          element: number
          label: 'Price ($)'
      - name: designer
        field:
          element: text
          label: Designer
      - name: type
        field:
          element: select
          label: Type
          options:
            - value: beauty
            - value: jewlery
            - value: clothes
      - name: image
        field:
          element: text
          label: Image
      - name: big_image
        field:
          element: text
          label: Big Image

# http://jekyllrb.com/docs/configuration/
permalink: blog/:title
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  products:
    output: true
    permalink: /:path/
defaults:
  -
    scope:
      path: '' # an empty string here means all files in the project
      type: posts # previously `post` in Jekyll 2.2.
    values:
      layout: post
  -
    scope:
      path: ''
      type: products
    values:
      layout: product
exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME
  - package.json
